# Generated by Django 3.2 on 2021-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='productimage'),
        ),
    ]
